<?php
$products = array(
    
    'NEBUCHADNEZZAR SEAT' => array("img_virtual/matrix1.jpg", "Escape the hard reality of a world led by robots. With it, you'll have superpowers that allow you to jump from a building to another, to fight like a pro and maybe, maybe save the world.", "14999.00$", "If you do not fear to be killed, jump in one of our seats and make your mind able to live another life. <br><small>Beware: Some people may try to kill you. You need to have a plug in your neck.<br> Plugs sold separately.</small>", "img_virtual/matrix2.jpg"),
    'DREAM SUITCASE' => array("img_virtual/inception1.jpg", "Share the dreams you have built with anyone who's asleep near you. You'll be able to create a new world where the reality is the one you have created and not the one you see everyday.", "999.00$", "Sedate yourself and your friends and enter shared dreams. You'll even be able to share dreams within your dreams! <br><small>Beware: do not enter too many dreams within your dreams, as your mind can stay stuck and you'll never wake up. <br>Sedatives sold separately.</small>" ,"img_virtual/inception2.jpg"),
    'X-1 BOOTSUIT' => array("img_virtual/rp11.jpg", "Put on the X-1 Haptic Bootsuit by IOI, and experience Virtual Reality in the Oasis like you've never have. The suit gives you comfort in both world. Rule the Oasi and rule the world!", "199.00$", "Disconnect yourself totally from the reality and jump into the Oasis and live a better experience with our bootsuit by IOI. You can purchase this item directly in the game for 30,000.00 Oasis Credits", "img_virtual/rp12.jpg"),
    'SAO HELMET' => array("img_virtual/sao1.jpg", "Purchase the Sword Art Online Helmet and jump in Aincrad and join other players from all over the world. Once you've put the helmet on, you're in ! Make allies and progress through the dungeon!", "249.00$", "Join a medieval RPG, a modern FPS or a fantasy RPG.<br><small>Beware: once you've put the helmet on, you're stuck in the game! </small>", "img_virtual/sao2.jpg"),
    'CARDBOARD' => array("img_virtual/card1.jpg", "Try an affordable Virtual Reality. Just put a smartphone in the cardboard and live simple experiences, like watching 360° photos or movies, play simple \"stare and shoot games\".", "6.99$", "Try our cardboard before experiencing other more dangerous virtual realities. <br><small>Beware: a long usage can procduce a little dazzling.</small>", "img_virtual/card2.jpg"),
    'CODE WARS' => array("img_virtual/cw.jpg", "Our best way to escape reality ! Codewars is where developers achieve code mastery through challenge. Train on kata in the dojo and reach your highest potential in many languages.", "FREE", "Codewars is an educational community for computer programming. On the platform, software developers train on programming challenges known as kata.These discrete programming exercises train a variety of skills in a variety of programming languages, and are completed within an online IDE.", "img_virtual/cw2.png")
    
    
);